name: test
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Get go version from .mise.toml
        id: goversion
        run: echo goversion=$(grep '^golang ' .mise.toml | cut -d'"' -f2) >> $GITHUB_OUTPUT
      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
      - name: Run tests
        run: go test ./...
