name: test
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Get go version from .mise.toml
        id: goversion
        run: echo goversion=$(grep '^golang ' .mise.toml | cut -d'"' -f2) >> $GITHUB_OUTPUT
      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
      - name: Run tests
        run: go test ./...
